---
# tasks file for postfix
 - name: Install Postfix Package
   package:
     name: postfix
     state: present

 - name: Postfix Configuration file
   template:
     src: main.cf.j2
     dest: /etc/postfix/main.cf
     mode: 0644
     owner: root
     group: root
   notify: restart postfix

 - name: Ensure Postfix Service is started
   service:
     name: postfix
     state: started  
