---
# tasks file for java
- name: Ensure java is installed (RedHat).
  package:
    name: "{{ java_packages }}"
    state: present
    enablerepo: "{{ java_enablerepo | default(omit, true) }}"
  when:
    - not java_install_from_source | bool
    - ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure java is installed (Debian).
  apt:
    name: "{{ java_packages }}"
    state: present
  when:
    - not java_install_from_source | bool
    - ansible_os_family == 'Debian'

- import_tasks: install-from-source.yml
  when: java_install_from_source | bool
  tags:
   - java_install_from_source
