---
 - include_vars: "{{ item }}"
   with_first_found:
     - "{{ ansible_distribution }}.yml"
     - "{{ ansible_os_family }}.yml"
   tags: httpd

 - name: Ensure apache is installed
   package:
     name: "{{ item }}"
     state: present
   with_items: "{{ httpd_packages }}"
   tags: httpd

 - name: Install Main Configuration file
   template:
     src: httpd.conf.j2
     dest: "{{ httpd_config }}"
     owner: root
     group: root
     mode: '0644'
   notify: restart httpd
   tags: httpd
  
 - name: Install certificate files
   include_tasks: certificates.yml
   tags: httpd

 - name: Install mod_ssl configuration file
   template:
     src: ssl.conf.j2
     dest: "{{ httpd_ssl_config }}" 
     owner: root
     group: root
     mode: '0644'
   notify: restart httpd
   tags: httpd

 - name: Ensure httpd service always running and enabled
   service:
    name: httpd
    state: started
    enabled: true
   tags: httpd
