 - hosts: randburg_webservers_int
   vars:
    groups_to_create:
      - name: jboss
        gid: 3000
    users:
      - name: Jboss Application admin account
        username: jboss
        groups: [test_users, nagios]
        generate_ssh_key: yes
        profile: |
          alias ll='ls -lah'
          alias cp='cp -iv'
        ssh_key:
         - "ssh-rsa AAAAB3NzaC1yc2EAAAA8bINXW9+EVaV74whLkTEem3IaaTYp1nli7O9QpffWqxPcIUj/FZaRGVMHUqsmn+RFOBg............"
   roles:
     - users

 - hosts: randburg_webservers_int
   vars:
    users:
      - name: Application account APP User 1
        username: app_user1
        groups: [test_users, nagios, jboss]
        profile: |
          alias ll='ls -lah'
          alias cp='cp -iv'
   roles:
     - users

 - hosts: randburg_webservers_int
   vars:
    users:
      - name: Application account APP User 2
        username: app_user2
        groups: [test_users, nagios, jboss]
        profile: |
          alias ll='ls -lah'
          alias cp='cp -iv'
   roles:
     - users

 - hosts: randburg_webservers_int
   vars:
    users:
      - name: Application account APP User 3
        username: app_user3
        groups: [test_users, nagios, jboss]
        shell: /bin/bash
        profile: |
          alias ll='ls -lah'
          alias cp='cp -iv'
   roles:
     - users
