---
# tasks file for httpd
#  include install.yml
#  include config.yml
#  include service.yml


- import_tasks: cust_facts.yml
  tags:
    - cust_facts

- import_tasks: install.yml
  tags:
    - install

- import_tasks: config.yml
  tags:
    - config

- import_tasks: service.yml
  tags:
    - service
